[workspace]
resolver = "2"

members = [
	"consensus",
	"ledger",
	"network",
	"types",
	"swiss_knife",
]


# helper = { path = "./swiss_knife/src/helper.rs" }

[profile.release]
debug = true

[profile.bench]
debug = true
