[package]
name = "abrahm"
version = "0.1.0"
authors = ["dkf <dannzor@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
themis = "0.13.0"
hex = "0.4.2"
rocksdb = "0.15.0"
rust-crypto = "^0.2"
serial_test = "*"
