[package]
name = "types"
version = "0.1.0"
authors = ["dkf <dannzor@outlook.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.3", features = ["json"] }
themis = "0.14.0"
serde_json = "1.0"

swiss_knife = { path = "../swiss_knife" }

[features]
default = []
