[package]
name = "types"
version = "0.1.0"
authors = ["dkf <dannzor@outlook.com>"]
edition = "2018"

[dependencies]
themis = "0.13.0"
swiss_knife = { path = "../swiss_knife" }

[features]
default = []
